version: '3.7'

services:
  timemachine:
    image: haijeploeg/samba-timemachine
    restart: unless-stopped
    env_file:
      - users.env
    networks:
      - timemachine
    volumes:
      - /data/backup:/backups
    ports:
      - 445:445/tcp
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

networks:
  timemachine:
