---

name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the git repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Prepare tags
      id: prep
      run: |
        RELEASE_TAG="${GITHUB_REF#refs/*/}"
        TAGS="haijeploeg/samba-timemachine:${GITHUB_REF#refs/*/},haijeploeg/samba-timemachine:latest"
        echo ::set-output name=release_tag::${RELEASE_TAG}
        echo ::set-output name=tags::${TAGS}

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.prep.outputs.tags }}
        platforms: |-
            linux/amd64
            linux/arm64
